# Generated by Django 5.2.6 on 2026-03-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0003_news_vaccinationcenter_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='family_member',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='VaccinationCenter',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
